# Generated by Django 5.1.2 on 2024-10-11 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='island',
            field=models.CharField(choices=[('salt_spring_island', 'Salt Spring Island'), ('vancouver_island', 'Vancouver Island'), ('mayne_island', 'Mayne Island'), ('galiano_island', 'Galiano Island')], default='Salt Spring Island', max_length=20),
        ),
    ]
