# Generated by Django 5.1.2 on 2024-10-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_island'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='view_type',
            field=models.CharField(choices=[('oceanfront', 'Oceanfront'), ('oceanview', 'Oceanview'), ('residential', 'Residential'), ('land', 'Land'), ('commercial', 'Commercial')], default='Oceanview', max_length=20),
        ),
    ]
