# Generated by Django 5.1.2 on 2024-10-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_view_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='island',
            field=models.CharField(choices=[('Salt Spring Island', 'Salt Spring Island'), ('vancouver_island', 'Vancouver Island'), ('mayne_island', 'Mayne Island'), ('galiano_island', 'Galiano Island')], default='Salt Spring Island', max_length=20),
        ),
    ]
