# Generated by Django 5.1.2 on 2024-10-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listing_island'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='island',
            field=models.CharField(choices=[('Salt Spring Island', 'Salt Spring Island'), ('Vancouver Island', 'Vancouver Island'), ('Mayne Island', 'Mayne Island'), ('Galiano Island', 'Galiano Island')], default='Salt Spring Island', max_length=40),
        ),
    ]
