# Generated by Django 5.1.2 on 2024-10-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listing_island'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='view_type',
            field=models.CharField(choices=[('Oceanfront', 'Oceanfront'), ('Oceanview', 'Oceanview'), ('Residential', 'Residential'), ('Land', 'Land'), ('Commercial', 'Commercial')], default='Oceanview', max_length=20),
        ),
    ]
