# Generated by Django 5.1.2 on 2024-10-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_listing_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Condo', 'Condo'), ('Townhouse', 'Townhouse'), ('Land', 'Land')], default='Land', max_length=40),
        ),
    ]
