# Generated by Django 5.1.2 on 2024-10-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_alter_listing_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='island',
            field=models.CharField(choices=[('Salt Spring Island', 'Salt Spring Island'), ('Vancouver Island', 'Vancouver Island'), ('Mayne Island', 'Mayne Island'), ('Galiano Island', 'Galiano Island')], default='Salt Spring Island', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Land', 'Land'), ('Commercial', 'Commercial')], default='Land', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='view_type',
            field=models.CharField(choices=[('oceanfront', 'Oceanfront'), ('oceanview', 'Oceanview'), ('residential', 'Residential'), ('land', 'Land'), ('commercial', 'Commercial')], default='Oceanview', max_length=20),
        ),
    ]
