# Generated by Django 5.1.2 on 2024-10-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_alter_listing_bathrooms_alter_listing_bedrooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='is_main',
        ),
        migrations.AddField(
            model_name='listing',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='listings/'),
        ),
    ]
