# Generated by Django 5.1.2 on 2024-10-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_remove_photo_is_main_listing_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
