# Generated by Django 5.1.2 on 2024-10-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_alter_listing_view_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='floor_plan_one',
            field=models.ImageField(blank=True, null=True, upload_to='listings/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='floor_plan_two',
            field=models.ImageField(blank=True, null=True, upload_to='listings/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='maps_plan',
            field=models.ImageField(blank=True, null=True, upload_to='listings/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='video',
            field=models.ImageField(blank=True, null=True, upload_to='listings/'),
        ),
    ]
