# Generated by Django 5.1.2 on 2024-10-13 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_alter_listing_floor_plan_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='floor_plan_one',
            field=models.FileField(blank=True, null=True, upload_to='listings/floor_plans/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='floor_plan_two',
            field=models.FileField(blank=True, null=True, upload_to='listings/floor_plans/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='maps_plan',
            field=models.FileField(blank=True, null=True, upload_to='listings/maps/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='listings/videos/'),
        ),
    ]
