# Generated by Django 5.1.2 on 2024-10-13 17:14

import listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_alter_listing_floor_plan_one_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='video',
        ),
        migrations.AddField(
            model_name='listing',
            name='video_or_3d_tour',
            field=models.URLField(blank=True, help_text='Enter a YouTube, Vimeo, or Matterport URL', max_length=255, null=True, validators=[listings.models.validate_video_or_matterport_url]),
        ),
    ]
