# Generated by Django 5.1.2 on 2024-10-14 17:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_remove_listing_video_listing_video_or_3d_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='maps_plan',
        ),
        migrations.AddField(
            model_name='listing',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='listing',
            name='zipcode',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='floor_plan_one',
            field=models.FileField(blank=True, null=True, upload_to='floor_plans/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='floor_plan_two',
            field=models.FileField(blank=True, null=True, upload_to='floor_plans/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='island',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='main_image',
            field=models.ImageField(null=True, upload_to='listings/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='video_or_3d_tour',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='view_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='listing_photos/'),
        ),
    ]
