# Generated by Django 5.1.2 on 2024-10-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_listing_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='island',
            field=models.CharField(choices=[('Salt Spring Island', 'Salt Spring Island'), ('Vancouver Island', 'Vancouver Island'), ('Mayne Island', 'Mayne Island'), ('Galiano Island', 'Galiano Island')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Land', 'Land'), ('Commercial', 'Commercial')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='view_type',
            field=models.CharField(choices=[('Oceanfront', 'Oceanfront'), ('Oceanview', 'Oceanview'), ('Residential', 'Residential'), ('Land', 'Land'), ('Non Ocean View', 'Non Ocean View'), ('Commercial', 'Commercial')], max_length=100),
        ),
    ]
